#define ST7789_2_DRIVER
#define TFT_WIDTH  240
#define TFT_HEIGHT 320
#define CGRAM_OFFSET
#define TFT_MISO -1
#define TFT_MOSI 23
#define TFT_SCLK 18
#define TFT_CS   15
#define TFT_DC   2
#define TFT_RST  4
#define TFT_BL   21
#define BACKLIGHT_ON HIGH
#define LOAD_GLCD
#define LOAD_FONT2
#define LOAD_FONT4
#define LOAD_FONT7
#define LOAD_FONT8
#define SMOOTH_FONT
#define SPI_FREQUENCY  40000000
#define SPI_READ_FREQUENCY 20000000
#define USE_HSPI_PORT
#define SPI_TOUCH_FREQUENCY 2500000