[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; 串口配置
monitor_speed = 115200
upload_speed = 921600

; 构建标志
build_flags = 
    -D ESP_PLATFORM
    -D CORE_DEBUG_LEVEL=0

; 库依赖
lib_deps = 
    h2zero/NimBLE-Arduino@^2.3.6
    bodmer/TFT_eSPI@^2.5.43
