#!/bin/bash

echo "=========================================="
echo "ESP32 JK BMS 显示系统 - GitHub上传向导"
echo "=========================================="
echo ""
echo "请按照以下步骤操作："
echo ""
echo "步骤1: 在GitHub上创建仓库"
echo "=========================================="
echo "1. 打开浏览器访问: https://github.com"
echo "2. 登录你的账号 (qq2292510929)"
echo "3. 点击右上角的 '+' 按钮"
echo "4. 选择 'New repository'"
echo ""
echo "在创建仓库页面填写："
echo "  - Repository name: ESP32-JKBMS-Display"
echo "  - Description: ESP32 JK BMS显示系统 - 战斗模式UI"
echo "  - 选择 'Private' (私有) 或 'Public' (公开)"
echo "  - 不要勾选任何初始化选项"
echo "  - 点击 'Create repository'"
echo ""
echo "创建完成后，GitHub会显示一个空仓库页面"
echo ""
echo "步骤2: 复制仓库地址"
echo "=========================================="
echo "在新建的仓库页面，你会看到:"
echo "  https://github.com/qq2292510929/ESP32-JKBMS-Display.git"
echo ""
echo "点击右侧的 'Code' 按钮"
echo "复制这个HTTPS地址"
echo ""
echo "步骤3: 添加远程仓库"
echo "=========================================="
echo "在终端中执行:"
echo ""
echo "cd ESP32_JKBMS_Display"
echo "git remote add origin https://github.com/qq2292510929/ESP32-JKBMS-Display.git"
echo ""
echo "步骤4: 推送到GitHub"
echo "=========================================="
echo "执行:"
echo ""
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "可能需要输入GitHub用户名和密码/Token"
echo ""
echo "步骤5: 验证上传成功"
echo "=========================================="
echo "刷新GitHub仓库页面"
echo "你应该能看到所有文件已上传"
echo ""
echo "=========================================="
echo "上传完成！"
echo "=========================================="
echo ""
echo "下一步："
echo "1. 在VSCode中打开这个仓库"
echo "2. 安装PlatformIO插件"
echo "3. 编译并上传到ESP32"
echo ""
echo "祝你使用愉快！⚡"
echo ""
